---
- name: Close AN INCIDENT
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - default_vars.yml

  tasks:
    - name: Close AN INCIDENT
      snow_record:
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        instance: "{{ SN_INSTANCE }}"
        state: present
        table: incident
        number: "{{ snow_inc_no }}"
        data:
          state: Closed
          short_description: "RH DEMO Create Incident"
          severity: 3
          priority: 2
          caller_id: "System Administrator"
          comments: "The is the test message for RH DEMO to Close SNOW incident"
      register: snow_var

    - name: VISUAL OUTPUT OF INCIDENT NUMBER
      debug:
        var: snow_var.record.number
